"""add_watchlist_overview_fields

Revision ID: aa2b5b81ef25
Revises: None
Create Date: 2026-06-15 20:44:30.819262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2b5b81ef25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_cache_id'), table_name='sentiment_cache')
    op.drop_index(op.f('ix_sentiment_cache_ticker'), table_name='sentiment_cache')
    op.drop_table('sentiment_cache')
    op.add_column('watchlists', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('watchlists', sa.Column('sector', sa.String(length=255), nullable=True))
    op.add_column('watchlists', sa.Column('industry', sa.String(length=255), nullable=True))
    op.add_column('watchlists', sa.Column('market_cap', sa.BigInteger(), nullable=True))
    op.add_column('watchlists', sa.Column('pe_ratio', sa.Float(), nullable=True))
    op.add_column('watchlists', sa.Column('dividend_yield', sa.Float(), nullable=True))
    op.add_column('watchlists', sa.Column('beta', sa.Float(), nullable=True))
    op.add_column('watchlists', sa.Column('eps', sa.Float(), nullable=True))
    op.add_column('watchlists', sa.Column('current_price', sa.Float(), nullable=True))
    op.add_column('watchlists', sa.Column('previous_close', sa.Float(), nullable=True))
    op.add_column('watchlists', sa.Column('website', sa.Text(), nullable=True))
    op.add_column('watchlists', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('watchlists', sa.Column('refresh_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlists', 'refresh_error')
    op.drop_column('watchlists', 'updated_at')
    op.drop_column('watchlists', 'website')
    op.drop_column('watchlists', 'previous_close')
    op.drop_column('watchlists', 'current_price')
    op.drop_column('watchlists', 'eps')
    op.drop_column('watchlists', 'beta')
    op.drop_column('watchlists', 'dividend_yield')
    op.drop_column('watchlists', 'pe_ratio')
    op.drop_column('watchlists', 'market_cap')
    op.drop_column('watchlists', 'industry')
    op.drop_column('watchlists', 'sector')
    op.drop_column('watchlists', 'company_name')
    op.create_table('sentiment_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), nullable=False),
    sa.Column('sentiment_score', sa.FLOAT(), nullable=True),
    sa.Column('sentiment_label', sa.VARCHAR(length=10), nullable=True),
    sa.Column('summary_paragraph', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_cache_ticker'), 'sentiment_cache', ['ticker'], unique=1)
    op.create_index(op.f('ix_sentiment_cache_id'), 'sentiment_cache', ['id'], unique=False)
    # ### end Alembic commands ###
